export const data = [
  {
    id: 1,
    image: "https://readymadeui.com/images/product9.webp",
    title: "Sole Elegance",
    price: 2000,
    quantity: 0,
    desc: "Premium sneakers for comfort and elegance.",
  },
  {
    id: 2,
    image: "https://readymadeui.com/images/product10.webp",
    title: "Urban Sneakers",
    price: 2500,
    quantity: 0,
    desc: "Stylish sneakers with urban durability.",
  },
  {
    id: 3,
    image: "https://readymadeui.com/images/product11.webp",
    title: "Velvet Boots",
    price: 3500,
    quantity: 0,
    desc: "Luxurious boots for trendsetters.",
  },
  {
    id: 4,
    image: "https://readymadeui.com/images/product12.webp",
    title: "Summit Hiking",
    price: 3000,
    quantity: 0,
    desc: "Reliable boots for every hiking trail.",
  },
  {
    id: 5,
    image: "https://readymadeui.com/images/product13.webp",
    title: "Zenith Glow",
    price: 4000,
    quantity: 0,
    desc: "Sleek sneakers with a glowing touch.",
  },
  {
    id: 6,
    image: "https://readymadeui.com/images/product14.webp",
    title: "Echo Elegance",
    price: 3000,
    quantity: 0,
    desc: "Elegant shoes with premium quality.",
  },
  {
    id: 7,
    image: "https://readymadeui.com/images/product15.webp",
    title: "Pumps",
    price: 3200,
    quantity: 0,
    desc: "Perfect pumps for every occasion.",
  },
  {
    id: 8,
    image: "https://readymadeui.com/images/product10.webp",
    title: "Blaze Burst",
    price: 2800,
    quantity: 0,
    desc: "Stylish and comfortable sneakers.",
  },
];
